services:
  agent:
    build:
      context: .
      dockerfile: services/agent/Dockerfile
      network: host
    container_name: agent
    depends_on:
      - mongo
    ports:
      - 4242:4242
    tty: true
    command: python -m deeppavlov_agent.run -ch http_client --cors
    environment:
      WIKIDATA_URL: http://wiki-parser:3013/model
      ENTITY_LINKING_URL: http://entity_linking:3006/model
  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  clone_tts:
    command: uvicorn tts:app --host 0.0.0.0 --reload --port 4344
    build:
      context: services/tts
      network: host
    ports:
      - 4344:4344
    environment:
      - CUDA_VISIBLE_DEVICES=0
  nemo:
    command: uvicorn main:app --host 0.0.0.0 --reload  --port 4343
    build:
      context: services/nemo
      network: host
    depends_on:
      - agent
    ports:
      - 4343:4343
  dff-bot-persona-skill:
    build:
      context: skills/dff
      network: host
    command: gunicorn --workers=1 --timeout 500 --graceful-timeout 500 server:app -b 0.0.0.0:8105 --reload --preload
    environment:
      WIKIDATA_URL: http://wiki-parser:3013/model
      ENTITY_LINKING_URL: http://entity_linking:3006/model
      GRAPH_DB_URL: http://graph_db:3055
  rule_based_response_selector:
    build:
      context: selectors/rule_based_response_selector
      network: host
    command: gunicorn --workers=1 server:app -b 0.0.0.0:3003
    volumes: [ ]
    ports:
      - 3003:3003
version: "3.7"
