services:
  clone_tts:
    command: uvicorn tts:app --host 0.0.0.0 --reload --port 4344
    build:
      context: .
    ports:
      - 4344:4344
    environment:
      - CUDA_VISIBLE_DEVICES=0

version: "3.7"